name: eclipse_shell
description: EclipseShell - High fidelity local music player with MoonShell-inspired UI.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.7.0'
dependencies:
  flutter:
    sdk: flutter
  
  # Versiones estables y armonizadas para evitar conflictos en la nube
  just_audio: 0.9.40
  audio_session: 0.1.21
  audio_service: 0.18.18
  
  # Para solicitar permisos de lectura de archivos locales
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
