name: Compilar EclipseShell APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Java JDK 17 (Sin búsqueda de caché)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # Eliminamos el parámetro de caché automático para evitar el fallo de rutas

      - name: 3. Configurar el entorno de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 4. Obtener dependencias del proyecto
        run: |
          flutter pub get

      - name: 5. Compilar APK
        run: |
          flutter build apk --release --no-pub

      - name: 6. Guardar el APK terminado
        uses: actions/upload-artifact@v4
        with:
          name: EclipseShell-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk