name: Compilar EclipseShell APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Esto te permite activar la compilación manualmente desde la web de GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Java JDK 17 (Requerido para Gradle moderno)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # Acelera futuras compilaciones guardando caché

      - name: 3. Configurar el entorno de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Guarda en caché el SDK de Flutter

      - name: 4. Limpiar y descargar dependencias de audio
        run: |
          flutter pub get

      - name: 5. Compilar instalador APK de manera limpia
        run: |
          flutter build apk --release --no-pub

      - name: 6. Subir el APK generado a la pestaña de artefactos
        uses: actions/upload-artifact@v4
        with:
          name: EclipseShell-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error